### PR TITLE
Allowing ingress controllers owncloud chart

### PR DESCRIPTION
**Pull request by carmat88**
Allowing ingress controllers owncloud chart.

### CODE REVIEW

**Comment by mcapuccini** [comment]
Great! I'll review it asap 🙂

**Review by mcapuccini — APPROVED** [review]
There were a couple of formatting errors, I just fixed them, it should work now. For the future please make sure to run `helm lint` before you push things. Now we just need to test the whole thing, and then we are ready to send a PR to the main repo.

**Comment by carmat88** [comment]
@mcapuccini As per our slack discussion, I've managed to locally test and thus install in a kubenow cluster the improved helm chart. However it seems that for local installation, it is necessary to run first the Helm command:

`helm dependency update`

otherwise it will show an error similar to:

`Error: found in requirements.yaml, but missing in charts/ directory: mariadb`.

I am guessing that this is transparently handled when using `helm install <paramenter> stable/owncloud` (but please correct me if I am wrong). Cheers

**Comment by mcapuccini** [comment]
Hi! Yes, that's ok. When you run from a remote repository that file is already there, while in our case we need to create it. Nothing to be concerned about.

**Pull request merged**
